image: "python:3.7.6"

before_script:
    - python --version
    - pip install -r requirements.txt

stages:
    - Scrape and email

run_app:
    stage: Scrape and email
    script:
        - python app.py 
